### ISSUE TITLE
RushHour csv files fouten

### ISSUE THREAD

**Issue by Jordy-prog** [minprog/heuristieken#12]
De csv files bevatten op het moment onnodige aanhalingstekens die het aflezen moeilijker maken.
Ook staan er verscheidene fouten in waarbij auto's elkaar overlappen of op de verkeerde plek staan.
Voor ons was het persoonlijk onhandig dat de auto's in de csv file een x en een y coördinaat hadden i.p.v. een row en een column.

Wij hebben de fouten verbetert en x en y omgezet naar row en column.

[data.zip](https://github.com/minprog/heuristieken/files/4091216/data.zip)

**Comment by okkevaneck** [comment]
Hi! Goed idee om de x en y coördinaten te splitsen, heb dat nu ook aangepast voor de nieuwe dataset. Jullie aangepaste dataset heb ik ook bekeken voor wijzigingen, maar volgens mij zijn jullie borden compleet anders dan de oorspronkelijke borden. Dat is inclusief de borden die geen overlap hebben. Klopt dit, of zit er misschien een logica achter die ik over het hoofd zie?

Tijdens het schrijven van een check50 voor Rush Hour kwam ik op één dubbele auto binnen het 12x12 bord, die is nu verwijderd. Verder is auto B voor het eerste 6x6 bord met 1 verlengd zodat hij overeenkomt met de PNG op de site. Hadden jullie nog andere dubbele gevonden? Het is voor mij heel lastig te controleren in jullie dataset, omdat ik weinig tot geen gelijkenis zie met de huidige borden.

**Comment by Jordy-prog** [comment]
Ik ga het even nalopen.

**Comment by Jordy-prog** [comment]
De huidige datasets staan met een x en y coördinaat. Wat precies andersom werkt van de rows en columns zoals je dat in code zou gebruiken (iniedergeval zoals wij het deden). Dus terwijl een maximale y betekent dat de auto bovenaan staat, is dat in je matrix slechts de eerste rij. Omdat wij erachter kwamen dat ongeveer iedere groep het op die manier deed, hebben wij de files omgezet naar een row en column structuur. Daarom lijkt het inderdaad alsof de borden compleet anders lijken, maar ze zijn hetzelfde. Ik zit niet meer genoeg in rushhour om te weten of er meer fouten waren, en heb ook geen code bij de hand om dat te testen. Sorry dat ik niet meer kan doen, wij zijn er persoonlijk achter gekomen door het bord handmatig op te lossen.

**Comment by okkevaneck** [comment]
Ahh okay, thanks! Dan ga ik er op die manier even naar kijken, waarschijnlijk kan ik ze dan wel omzetten en een diff maken.  
Geen probleem, zal er nog een extra keer naar kijken. Het is al heel fijn om jullie gedachten gang te weten. Gelukkig heb ik ook nog een analoge versie in de kast staan, dus ik ga ff schuiven ;)

**Comment by okkevaneck** [comment]
Er bleek uiteindelijk een auto dubbel te staan in het 12x12. Deze is verwijdered en de data heeft nu row en column velden ipv x en y. Deze issue kan gesloten worden @WouterVrielink.
