### ISSUE TITLE
Scorefunctie Chips & Circuits

### ISSUE THREAD

**Issue by WouterVrielink** [minprog/heuristieken#13]
Op het moment is het vrij lastig om een netlist compleet te leggen. De scorefunctie geeft echter pas een mogelijkheid tot geven van punten aan een oplossing als alle nets liggen. 

Huidige oplossing is simpelweg het percentage van gelegde nets gebruiken als score, maar het liefst willen we dit integreren met de scorefunctie. 

Er zijn in ieder geval twee opties voor het aanpassen van de scorefunctie:
- **Kortsluiting toestaan:** (op voorstel van Bas Terwijn) leggen van twee paden op dezelfde plek kan, maar hier krijg je dan ook strafpunten voor. 
- **Kostenverhoging voor nets die niet gelegd zijn:** net als bij de huidige versie van RailNL een manier verzinnen om een incomplete oplossing ook punten toe te wijzen. Bijvoorbeeld door nets die niet gelegd zijn strafpunten te geven.

Beide opties hebben voor én nadelen... Als iemand andere suggesties heeft, of zelf één van de twee methodes heeft gebruikt hoor ik het graag!

**Comment by okkevaneck** [comment]
Aankomende editie zullen we kijken of we het probleem kunnen met oplossen met alleen het toestaan van kortsluitingen. De penalty van een kortsluiting moet hoog genoeg zijn dat je hem altijd wil verleggen, dus het huidige idee is om voor iedere overlapping van wires een penalty ter grootte van één layer te geven.  
Verder is het voor de studenten fijn om iets eerder met het optimaliseren van oplossingen te kunnen werken. Daarom gaan we kijken naar één (of een kleine serie) van makkelijke borden om op te lossen.  

Deze twee veranderingen resulteren in:

1. Een nieuwe scoringsfunctie, waarbij penalty's voor kortsluitingen worden meegerekend.
2. Een nieuw bord of een serie van nieuwe borden die relatief makkelijk zijn om op te lossen

**Comment by WouterVrielink** [comment]
Dit lijkt de meeste problemen voorlopig te hebben opgelost.
