### ISSUE TITLE
Check50: Amstelhaege

### ISSUE THREAD

**Issue by JopRijks** [minprog/heuristieken#28]
De check50 van Amstelhaege houdt geen rekening met de verplichte vrijstand bij het berekenen van de score.

In de opdracht staat:
In geval van percentuele waardevermeerdering per meter is de toename niet cumulatief. Een maison met twee meter **extra vrijstand** is dus 12.0% meer waard, niet 12.36%.

Check50 gebruikt gewoon de afstand tot het huis dat het meest dichtbij staat. Hier moet dus de verplichte vrijstand per huis vanaf. Het is een kleine aanpassing maar we hebben een tijd lang gezocht naar het probleem.

**Comment by Jelleas** [comment]
Recentelijk opgelost! :)

https://github.com/minprog/theorie-check50/commit/7de6ee55722f980a37f26e191aa2bb70b43b9297
