### ISSUE TITLE
X en Y verkeerd in RailNL

### ISSUE THREAD

**Issue by MarijnDoeve** [minprog/heuristieken#34]
In de datafiles van RailNL staan de x en y coördinaten omgedraaid. 
Dat geeft mooie plaatjes! 😊
![Holland](https://user-images.githubusercontent.com/11721067/120883934-7d45ba80-c5e0-11eb-97c3-e87c6af77aeb.png)
![Nationaal](https://user-images.githubusercontent.com/11721067/120883935-7f0f7e00-c5e0-11eb-8498-848d21cf2be0.png)

**Comment by WouterVrielink** [comment]
Fixed!
