### ISSUE TITLE
Duidelijker eindpunt schetsen Heuristieken

### ISSUE THREAD

**Issue by Jelleas** [minprog/heuristieken#36]
Vergelijkingen tussen algoritmes moet terugkomen.

Concrete instructies voor het draaien van experimenten. 

Het gaat om het vinden van het beste resultaat en hoe. Tijd / geheugen is bijzaak.

**Comment by WouterVrielink** [comment]
Komt in een college in de derde week + is al extra onder aandacht gebracht bij de experiment-milestone!
